spring:
  datasource:
    url: jdbc:postgresql://dpg-d47lgefdiees739f92ag-a.singapore-postgres.render.com:5432/unitime_db?sslmode=require
    username: unitime_db_user
    password: DZAwKlrR0H830jh2HmApPFq5AHrQpAj5
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:4a9f1e2c7b4d9f2a9c1e7b4d9f2a9c1e}
  access-token-validity-ms: 3600000
  refresh-token-validity-ms: 1209600000


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace




openai:               # 배포시 이걸로
  api-key: ${OPENAI_API_KEY}
